name: NestJS CI Build
run-name: ${{ github.actor }} is running CI build 🚀
on: [push] #push 이벤트일때 작동
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Print build status
        run: echo "✅ Build completed successfully!"
